#!/usr/bin/env bash
# Pre-loop sanity checks for a ROCm KDA Pilot Humanize/RLCR run.
#
# Motivated by loop 01 (see results/loop-01-flashattn-gfx950.md),
# where two avoidable failures cost real time:
#   1. A Codex model-name typo (`gpt5.5` vs `gpt-5.5`) was accepted at loop start,
#      persisted into immutable loop state, and only surfaced when the first
#      reviewer call failed -- forcing a full loop cancel + restart.
#   2. The FlyDSL worktree lacked a built `build-fly`/`_mlir` binding tree the
#      test harness imports from, requiring a manual symlink mid-loop.
#
# Run this BEFORE `/humanize:start-rlcr-loop`. It only checks/reports; with
# --fix-bindings it will additionally wire a missing build tree from a sibling
# built FlyDSL checkout.
#
# Usage:
#   scripts/preflight.sh /path/to/FlyDSL-worktree [--codex-model gpt-5.5:xhigh]
#                                                 [--build-from /path/to/built-FlyDSL]
#                                                 [--fix-bindings]
set -uo pipefail

FLYDSL_ROOT=""
CODEX_MODEL="gpt-5.5:xhigh"
BUILD_FROM=""
FIX_BINDINGS=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --codex-model) CODEX_MODEL="$2"; shift 2 ;;
    --build-from) BUILD_FROM="$2"; shift 2 ;;
    --fix-bindings) FIX_BINDINGS=1; shift ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) FLYDSL_ROOT="$1"; shift ;;
  esac
done

if [[ -z "$FLYDSL_ROOT" ]] || ! git -C "$FLYDSL_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "usage: scripts/preflight.sh /path/to/FlyDSL-worktree [...]" >&2
  exit 2
fi
FLYDSL_ROOT="$(cd "$FLYDSL_ROOT" && pwd)"

fail=0
ok()   { echo "  [ok]   $*"; }
warn() { echo "  [warn] $*"; }
bad()  { echo "  [FAIL] $*"; fail=1; }

echo "== ROCm KDA Pilot preflight =="
echo "worktree: $FLYDSL_ROOT"

# --- 1. Codex model name resolves against the configured backend ----------------
echo "-- Codex model name --"
CODEX_MODEL_NAME="${CODEX_MODEL%%:*}"   # strip :effort suffix
if ! command -v codex >/dev/null 2>&1; then
  warn "codex CLI not on PATH; cannot verify model name '$CODEX_MODEL_NAME'."
else
  # A cheap end-to-end probe: ask the model to echo one token. If the deployment
  # name is wrong (e.g. missing hyphen) this fails fast HERE, not after round 0.
  if echo "reply with the single word OK" \
       | timeout 90 codex exec --disable codex_hooks -m "$CODEX_MODEL_NAME" \
           -c model_reasoning_effort=low --full-auto -C "$FLYDSL_ROOT" >/tmp/_kda_codex_probe 2>&1 \
     && grep -qi "OK" /tmp/_kda_codex_probe; then
    ok "codex model '$CODEX_MODEL_NAME' resolves and responds."
  else
    bad "codex model '$CODEX_MODEL_NAME' did NOT resolve/respond. Check the exact deployment name (a missing hyphen like 'gpt5.5' vs 'gpt-5.5' will be accepted by the loop but fail at first review). Probe output:"
    sed 's/^/         /' /tmp/_kda_codex_probe | tail -5
  fi
fi

# --- 2. FlyDSL build/runtime bindings importable --------------------------------
echo "-- FlyDSL _mlir bindings --"
PYTHONPATH="$FLYDSL_ROOT/python:$FLYDSL_ROOT:${PYTHONPATH:-}" \
  python3 -c "import flydsl._mlir" >/dev/null 2>&1
if [[ $? -eq 0 ]]; then
  ok "flydsl._mlir importable from this worktree."
else
  if [[ -e "$FLYDSL_ROOT/build-fly/python_packages/flydsl/_mlir" || -L "$FLYDSL_ROOT/python/flydsl/_mlir" ]]; then
    warn "build-fly present but flydsl._mlir not importable; check LD_LIBRARY_PATH (see runenv below)."
  elif [[ $FIX_BINDINGS -eq 1 && -n "$BUILD_FROM" && -d "$BUILD_FROM/build-fly/python_packages/flydsl/_mlir" ]]; then
    ln -sfn "$BUILD_FROM/build-fly/python_packages/flydsl/_mlir" "$FLYDSL_ROOT/python/flydsl/_mlir"
    ln -sfn "$BUILD_FROM/build-fly" "$FLYDSL_ROOT/build-fly"
    # keep the symlinks out of git locally
    COMMON="$(git -C "$FLYDSL_ROOT" rev-parse --git-common-dir)"
    for ig in build-fly; do grep -qxF "$ig" "$COMMON/info/exclude" 2>/dev/null || echo "$ig" >> "$COMMON/info/exclude"; done
    ok "wired build-fly + python/flydsl/_mlir from $BUILD_FROM (symlinks, git-excluded)."
  else
    bad "flydsl._mlir NOT importable and no build tree to wire. Either build this worktree, or pass --build-from /path/to/built-FlyDSL --fix-bindings (a sibling checkout whose C++ delta vs this worktree is codegen-irrelevant)."
  fi
fi

# --- 3. Emit a runenv.sh the loop can source ------------------------------------
echo "-- runenv --"
RUNENV="$FLYDSL_ROOT/.humanize/kernel-agent/runenv.sh"
mkdir -p "$(dirname "$RUNENV")"
MLIR_LIBS=""
if [[ -L "$FLYDSL_ROOT/python/flydsl/_mlir" ]]; then
  MLIR_LIBS="$(readlink -f "$FLYDSL_ROOT/python/flydsl/_mlir")/_mlir_libs"
elif [[ -d "$FLYDSL_ROOT/build-fly/python_packages/flydsl/_mlir/_mlir_libs" ]]; then
  MLIR_LIBS="$FLYDSL_ROOT/build-fly/python_packages/flydsl/_mlir/_mlir_libs"
fi
{
  echo "# Source before running the FlyDSL harness in this worktree. Generated by preflight.sh."
  echo "export PYTHONPATH=\"$FLYDSL_ROOT/python:$FLYDSL_ROOT:\${PYTHONPATH:-}\""
  [[ -n "$MLIR_LIBS" ]] && echo "export LD_LIBRARY_PATH=\"$MLIR_LIBS:\${LD_LIBRARY_PATH:-}\""
} > "$RUNENV"
ok "wrote $RUNENV"

# --- 4. Shared/stale build-fly detection (loop fa-fp8 lesson) -------------------
# Motivated by the fp8 FlashAttention loop, where ~5 rounds were lost to a single
# environment trap: this worktree's build-fly was a TOP-LEVEL SYMLINK to one
# shared build dir reused by ~10 sibling worktrees. When that shared build lagged
# the current source, pytest failed repo-wide with API-drift ImportErrors in
# modules the branch never touched -- easy to misattribute to your own diff. The
# fix is a PRIVATE self-consistent build (FLY_BUILD_DIR=...) plus a conftest that
# honors it. This check surfaces the trap at round 0 instead of at finalization.
echo "-- build-fly sharing / staleness --"
BUILD_FLY="$FLYDSL_ROOT/build-fly"
if [[ -L "$BUILD_FLY" ]]; then
  TARGET="$(readlink -f "$BUILD_FLY" 2>/dev/null || true)"
  # Count how many of this repo's worktrees resolve build-fly to the same target.
  shared_n=0
  while IFS= read -r wt; do
    [[ -z "$wt" ]] && continue
    wt_target="$(readlink -f "$wt/build-fly" 2>/dev/null || true)"
    [[ -n "$wt_target" && "$wt_target" == "$TARGET" ]] && shared_n=$((shared_n+1))
  done < <(git -C "$FLYDSL_ROOT" worktree list --porcelain 2>/dev/null | awk '/^worktree /{print $2}')
  if [[ "$shared_n" -ge 2 ]]; then
    warn "build-fly is a SHARED symlink -> $TARGET (used by $shared_n worktrees)."
    warn "If it lags this worktree's source, pytest will fail repo-wide with API-drift"
    warn "ImportErrors in untouched modules. Build a PRIVATE tree and export it:"
    warn "    FLY_BUILD_DIR=/tmp/flydsl-\$(basename \$PWD)-build bash scripts/build.sh -j\$(nproc)"
    warn "    export FLY_BUILD_DIR=/tmp/flydsl-\$(basename \$PWD)-build   # used by run_tests.sh + conftest"
  else
    ok "build-fly is a symlink but not shared across worktrees."
  fi
else
  ok "build-fly is not a shared symlink."
fi
# conftest must honor FLY_BUILD_DIR, else pytest silently reverts to the shared build.
CONFTEST="$FLYDSL_ROOT/tests/conftest.py"
if [[ -f "$CONFTEST" ]]; then
  if grep -q "FLY_BUILD_DIR" "$CONFTEST" 2>/dev/null; then
    ok "tests/conftest.py honors FLY_BUILD_DIR (private build is testable under pytest)."
  else
    warn "tests/conftest.py does NOT reference FLY_BUILD_DIR: pytest may pin the default"
    warn "build-fly on sys.path[0] and ignore a private build. Verify before relying on a"
    warn "private build for the pytest gate (direct 'python3' honors PYTHONPATH; pytest may not)."
  fi
fi

# --- 5. Acceptance-gate executability smoke (loop fa-fp8 lesson) ----------------
# The merge gate (RUN_TESTS_FULL=1 run_tests.sh: pytest + examples + MLIR FileCheck)
# could not even RUN for several rounds because of environment/dep drift discovered
# only at finalization. Treat "the gate is not executable here" as a round-0 blocker.
echo "-- acceptance-gate executability --"
if [[ -f "$FLYDSL_ROOT/scripts/run_tests.sh" ]]; then
  ok "scripts/run_tests.sh present."
  if grep -q "multi_gpu" "$FLYDSL_ROOT/scripts/run_tests.sh" 2>/dev/null; then
    ok "run_tests.sh references multi_gpu marker (CI split handled)."
  else
    warn "run_tests.sh has no multi_gpu handling: an 8-GPU test (e.g. allreduce) may"
    warn "fail-fast the whole gate on a single-node box. Confirm the documented CI split."
  fi
  warn "Run the full gate ONCE before feature work to confirm it executes end-to-end:"
  warn "    FLY_BUILD_DIR=<private> RUN_TESTS_FULL=1 bash scripts/run_tests.sh   # round-0 smoke"
else
  warn "scripts/run_tests.sh not found; cannot pre-verify the merge gate."
fi

# --- 6. GPU present -------------------------------------------------------------
echo "-- GPU --"
if command -v rocm-smi >/dev/null 2>&1 && rocm-smi --showid >/dev/null 2>&1; then
  ok "rocm-smi reports a GPU."
else
  warn "rocm-smi not available or no GPU; device-tier tests will not run."
fi

echo "== preflight: $([[ $fail -eq 0 ]] && echo PASS || echo FAIL) =="
exit $fail
